In [67]:
import pandas as pd

In [68]:
df=pd.read_csv("customer_shopping_data.csv")

In [69]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Product Type,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,60,Female,Sweater,Apparel,84.25,Delaware,S,Teal,Winter,NaN,No,Standard,Yes,32,Cash,Fortnightly
1,2,67,Male,Shirt,Apparel,93.52,New York,XL,Violet,Winter,1.6,No,Free Shipping,Yes,33,Credit Card,Weekly
2,3,64,Male,Shorts,Apparel,119.49,New Hampshire,L,Yellow,Spring,NaN,No,Free Shipping,Yes,8,Bank Transfer,Quarterly
3,4,25,Male,Sandals,Footwear,49.36,Massachusetts,L,Green,Summer,NaN,Yes,Express,No,52,Debit Card,Fortnightly
4,5,34,Female,Dress,Apparel,90.04,Louisiana,S,Green,Winter,NaN,Yes,2-Day Shipping,Yes,55,PayPal,Monthly

In [70]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Product Type,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
10395,10396,36,Female,Belt,Bags & Accessories,79.28,West Virginia,L,Charcoal,Spring,4.7,No,Express,Yes,46,PayPal,Weekly
10396,10397,40,Male,Shorts,Apparel,77.62,West Virginia,XXL,Purple,Spring,NaN,No,2-Day Shipping,Yes,12,Cash,Quarterly
10397,10398,34,Female,Jeans,Apparel,108.42,New York,S,Turquoise,Fall,4.6,Yes,Free Shipping,No,11,Venmo,Quarterly
10398,10399,63,Male,Belt,Bags & Accessories,19.66,Florida,L,Violet,Fall,NaN,Yes,2-Day Shipping,No,7,Venmo,Fortnightly
10399,10400,18,Male,Belt,Bags & Accessories,77.03,Arkansas,XXL,Purple,Spring,4.2,No,2-Day Shipping,No,4,Debit Card,Fortnightly

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10400 entries, 0 to 10399
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             10400 non-null  int64
 1   Age                     10400 non-null  int64
 2   Gender                  10400 non-null  object
 3   Item Purchased          10400 non-null  object
 4   Product Type            9567 non-null   object
 5   Purchase Amount         10400 non-null  float64
 6   Location                10400 non-null  object
 7   Size                    10400 non-null  object
 8   Color                   10400 non-null  object
 9   Season                  10400 non-null  object
 10  Review Rating           9354 non-null   float64
 11  Subscription Status     10400 non-null  object
 12  Shipping Type           10400 non-null  object
 13  Discount Applied        10400 non-null  object
 14  Previous Purchases      10400 non-null  int64
 15  Payment Method          10400 non-null  object
 16  Frequency of Purchases  10400 non-null  object
dtypes: float64(2), int64(3), object(12)
memory usage: 1.3+ MB

In [72]:
df.describe()

,Customer ID,Age,Purchase Amount,Review Rating,Previous Purchases
count,10400.000000,10400.000000,10400.000000,9354.000000,10400.000000
mean,5200.500000,43.510673,67.204585,2.998803,30.011635
std,3002.365734,14.897369,30.274672,1.159991,16.971803
min,1.000000,18.000000,15.010000,1.000000,1.000000
25%,2600.750000,31.000000,41.030000,2.000000,15.000000
50%,5200.500000,43.000000,66.780000,3.000000,30.000000
75%,7800.250000,56.000000,93.772500,4.000000,45.000000
max,10400.000000,69.000000,119.990000,5.000000,59.000000

In [73]:
print(df.duplicated().sum())
print(df[df.duplicated()])

0
Empty DataFrame
Columns: [Customer ID, Age, Gender, Item Purchased, Product Type, Purchase Amount, Location, Size, Color, Season, Review Rating, Subscription Status, Shipping Type, Discount Applied, Previous Purchases, Payment Method, Frequency of Purchases]
Index: []

In [74]:
df.isnull().sum()

Customer ID                  0
Age                          0
Gender                       0
Item Purchased               0
Product Type               833
Purchase Amount              0
Location                     0
Size                         0
Color                        0
Season                       0
Review Rating             1046
Subscription Status          0
Shipping Type                0
Discount Applied             0
Previous Purchases           0
Payment Method               0
Frequency of Purchases       0
dtype: int64

In [75]:
# Fill the missing values
print(df['Product Type'].unique())

['Apparel' 'Footwear' 'Outerwear' 'Luxury Goods' 'Bags & Accessories' nan]

In [76]:
print(df.groupby('Item Purchased')['Product Type'].unique())

Item Purchased
Belt          [Bags & Accessories, nan]
Blouse                   [Apparel, nan]
Boots                   [Footwear, nan]
Coat                   [Outerwear, nan]
Dress                    [Apparel, nan]
Handbag       [Bags & Accessories, nan]
Hat           [nan, Bags & Accessories]
Jacket                 [Outerwear, nan]
Jeans                    [Apparel, nan]
Sandals                 [Footwear, nan]
Scarf                    [Apparel, nan]
Shirt                    [Apparel, nan]
Shoes                   [Footwear, nan]
Shorts                   [Apparel, nan]
Skirt                    [Apparel, nan]
Sunglasses          [Luxury Goods, nan]
Sweater                  [Apparel, nan]
Watch               [Luxury Goods, nan]
Name: Product Type, dtype: object

In [78]:

pt_map = {
    'Belt': 'Bags & Accessories',
    'Blouse': 'Apparel',
    'Boots': 'Footwear',
    'Coat': 'Outerwear',
    'Dress': 'Apparel',
    'Handbag': 'Bags & Accessories',
    'Hat': 'Bags & Accessories',
    'Jacket': 'Outerwear',
    'Jeans': 'Apparel',
    'Sandals': 'Footwear',
    'Scarf': 'Apparel',
    'Shirt': 'Apparel',
    'Shoes': 'Footwear',
    'Shorts': 'Apparel',
    'Skirt': 'Apparel',
    'Sunglasses': 'Luxury Goods',
    'Sweater': 'Apparel',
    'Watch': 'Luxury Goods'
}


df['Product Type'] = df['Product Type'].fillna(df['Item Purchased'].map(pt_map))


print(df['Product Type'].isnull().sum())

0

In [79]:
df["Product Type"].isnull().sum()

np.int64(0)

In [80]:
df["Review Rating"] = df.groupby("Product Type")["Review Rating"].transform(
    lambda x: x.fillna(x.mean())
)

In [81]:
df["Review Rating"].isnull().sum()

np.int64(0)

In [82]:
df.columns=df.columns.str.lower()

In [83]:
df.columns=df.columns.str.replace(" ", "_")

In [84]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'product_type',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [85]:
#Feature Engineering

In [86]:
#creating column Age_Group
labels=["young", "adult", "middle_aged", "senior"]
df['age_group']=pd.qcut(df["age"],q=4, labels=labels)
df[["age","age_group"]].head(10)

   age    age_group
0   60       senior
1   67       senior
2   64       senior
3   25        young
4   34        adult
5   37        adult
6   68       senior
7   52  middle_aged
8   26        young
9   28        young

In [87]:
#creating column purchase freq days
unique_values = df['frequency_of_purchases'].unique()
print(unique_values)

['Fortnightly' 'Weekly' 'Quarterly' 'Monthly' 'Bi-Weekly' 'Annually']

In [88]:
frequency_mapping={'Fortnightly':14, 'Weekly':7, 'Annually':365, 'Quarterly':90, 'Bi-Weekly':14, 'Monthly':30,
 'Every 3 Months':120}

In [89]:
df["purchase_freq_days"]=df["frequency_of_purchases"].map(frequency_mapping)

In [90]:
df[["purchase_freq_days","frequency_of_purchases"]].head()

   purchase_freq_days frequency_of_purchases
0                  14            Fortnightly
1                   7                 Weekly
2                  90              Quarterly
3                  14            Fortnightly
4                  30                Monthly

In [111]:
df.to_csv('cleaned_customer_shopping_data.csv', index=False)